Test cart controller
piotr-grosicki/project-jdp-2207-01 pull request #18
Opened 2022-07-13 19:37 UTC by AndrzejRajczyk

2022-07-13 20:44 UTC, kubajaro requested changes
Pull Request dotyczy testów controllera cart, a brakuje testów w plikach

2022-07-14 08:49 UTC, GrzeSzk commented
Andrzej, a w tych testach nie powinno być jeszcze dodane //clean up na końcu, czy to nie jest konieczne?

2022-07-15 08:21 UTC, AndrzejRajczyk commented
panowie testy są w postmanie

2022-07-16 16:44 UTC, danielmisior commented
Nie rozumiem czemu miały służyć zmiany nazw kolumn w bazie danych i tabeli orders na or.

2022-07-16 16:56 UTC, AndrzejRajczyk commented
or - powinno byc oczywiście order. Nie wiem skąd tak sie zapisało mój IJ ma order lokalnie. 
nazwy musiałem zmienić, bo mieliśmy nie stosować nazw nazwa_Id a zamiast tego stosowac camele nazwaId.
Ponieważ kontrollery miały już nazwaId dostosowałem encje

2022-07-17 12:01 UTC, kubajaro approved these changes

2022-07-18 06:53 UTC, piotr-grosicki reviewed
w bazach danych raczej konwencja jest do uzywania `_` a nie camel case :)

2022-07-18 17:00 UTC, closed without merging