JDP220701-3 Added CartController and CartDto
piotr-grosicki/project-jdp-2207-01 pull request #8
Opened 2022-06-30 04:17 UTC by rdna2

2022-06-30 05:46 UTC, piotr-grosicki requested changes

2022-06-30 05:46 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @GetMapping(value = "getNewCart")
wszystkie inne controllery korzystaja z innej konwencji, bez nazywania sciezek + path variables

2022-06-30 17:45 UTC, rdna2 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @GetMapping(value = "getNewCart")
Poprawiony kontroler - bez nazywania sciezek i bez path variables.

2022-06-30 19:47 UTC, rdna2 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @GetMapping(value = "getNewCart")
Na wszelki wypadek zmieniłem wszystkie @RequestParam na @PathVariable.

2022-07-01 14:10 UTC, danielmisior commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @GetMapping(value = "getProductsFromCart")
Nie lepiej byłoby do wartości przypisać cartId, a nie getProductsFromCart?

2022-07-01 14:11 UTC, danielmisior commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +      @PostMapping(value = "addProductToCart", consumes = APPLICATION_JSON_VALUE)
Tu tak samo

2022-07-01 14:12 UTC, danielmisior commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @DeleteMapping(value = "deleteProductFromCart")
Tu też

2022-07-01 14:13 UTC, danielmisior commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PostMapping(value = "addNewOrder", consumes = APPLICATION_JSON_VALUE)
A tu według mnie może obyć się bez 'value'. Jeśli się mylę - poprawcie mnie :)

2022-07-01 15:56 UTC, rdna2 commented on src/main/java/com/kodilla/ecommercee/controller/CartController.java
> +    @PostMapping(value = "addNewOrder", consumes = APPLICATION_JSON_VALUE)
Poprawione.

2022-07-01 16:07 UTC, danielmisior approved these changes
Nie wiem czy dwie metody z dodatkowym productId zadziałają bez dodania ich do value, ale to już wyjdzie w testach :)

2022-07-01 20:05 UTC, Kazula92 approved these changes

2022-07-02 09:35 UTC, merged